version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 5
    groups:
      minor-or-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      minor-or-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
  - package-ecosystem: rust-toolchain
    directory: "/"
    schedule:
      interval: daily
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
