version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Minor updates
  - package-ecosystem: cargo
    versioning-strategy: lockfile-only
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  # Major updates
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-patch
          - version-update:semver-minor
