[changelog]
trim = false
protect_breaking_commits = true
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}]\
    {%- if release_link -%}\
        ({{ release_link }})\
    {% endif %} \
    - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
### {{ group | upper_first }}

{% for commit in commits | unique(attribute="message")  -%}
{% if commit.scope -%}
    - _({{commit.scope}})_ {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message }}\
        {% if commit.links %} \
            ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%})\
        {% endif %}
{% else -%}
    - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor %}
"""

commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^perf", group = "Changed" },
  { message = "^refactor", group = "Changed" },
  { message = "^deprecate", group = "Deprecated" },
  { message = "^remove", group = "Removed" },
  { message = "^security", group = "Security" },
  { message = ".*forward port", group = "other" },
  { message = "^.*", skip = true },
]
