name: os-check
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
defaults:
  run:
    shell: bash
env:
  CI: "true"
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  NEXTEST_PROFILE: "ci"
jobs:
  os-check:
    runs-on: ${{ matrix.os }}
    name: os-check / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v6.0.3
        with:
          submodules: true
      - uses: ./.github/actions/install-deps
        with:
          for-image: "${{ matrix.os }}"
      - uses: actions-rust-lang/setup-rust-toolchain@v1.16.1
      - uses: mozilla-actions/sccache-action@v0.0.10
      - uses: taiki-e/install-action@v2.81.4
        with:
          tool: cargo-nextest
      - name: cargo nextest run
        run: cargo nextest run --locked --all-features --workspace
