name: release-plz
permissions:
  pull-requests: write
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
defaults:
  run:
    shell: bash

jobs:
  # Release unpublished packages.
  release:
    name: release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: create new release
        uses: release-plz/action@v0.5.110
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.PUBLISH_TOKEN }}

  # Create a PR with the new versions and changelog, preparing the next release.
  release-pr:
    name: release-pr
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: release-plz-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: dtolnay/rust-toolchain@stable
      - name: create release pr
        uses: release-plz/action@v0.5.110
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
